apiVersion: v1
kind: Service
metadata:
  name: my-mongo-external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    role: mongo
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 27017
